services:
  jlab:
    image: jupyter/scipy-notebook:python-3.11
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_TOKEN=estategis
      - LD_LIBRARY_PATH=/opt/conda/lib
    volumes:
      - ./supclassann:/home/jovyan/work
      - ./requirements.txt:/tmp/requirements.txt:ro
    command: >
      bash -lc "
      mamba install -y -c conda-forge sqlite=3.46.1 libsqlite=3.46.1 gdal=3.8 rasterio=1.3.10 &&
      pip install --no-cache-dir -r /tmp/requirements.txt &&
      start.sh jupyter lab --LabApp.token=estategis --LabApp.allow_origin='*'"
    restart: unless-stopped